-- ============================================
-- SINCRONIZAR SCHEMA DA TABELA PETS
-- Adiciona colunas que existem no Drizzle mas não no banco
-- ============================================

-- DADOS FÍSICOS AVANÇADOS
ALTER TABLE pets ADD COLUMN IF NOT EXISTS size VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS coat_type VARCHAR(30);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS is_castrated BOOLEAN;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS last_heat_date TIMESTAMP;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS sex VARCHAR(10);

-- PERFIL COMPORTAMENTAL
ALTER TABLE pets ADD COLUMN IF NOT EXISTS energy_level VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS dog_sociability VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS human_sociability VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS play_style VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS correction_sensitivity VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS human_focus VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS fear_triggers JSONB DEFAULT '[]';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS calming_technique VARCHAR(30);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS equipment_restrictions JSONB DEFAULT '[]';

-- RESTRIÇÕES DE CONVÍVIO
ALTER TABLE pets ADD COLUMN IF NOT EXISTS sociability_level VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS anxiety_separation VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS room_preference VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS convivence_restrictions JSONB DEFAULT '[]';

-- MÉTRICAS DE TEMPERAMENTO
ALTER TABLE pets ADD COLUMN IF NOT EXISTS confidence_level INTEGER;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS impulsivity_level INTEGER;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS resilience_level INTEGER;

-- ALIMENTAÇÃO
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_brand VARCHAR(200);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_type VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_amount INTEGER;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_stock_grams INTEGER;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_stock_last_update TIMESTAMP;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS feeding_instructions TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_preparation VARCHAR(30);

-- SAÚDE E ALERGIAS
ALTER TABLE pets ADD COLUMN IF NOT EXISTS has_food_allergy BOOLEAN;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_allergy_details TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS has_medication_allergy BOOLEAN;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS medication_allergy_details TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS has_chronic_condition BOOLEAN;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS chronic_condition_details TEXT;

-- PROTOCOLO DE EMERGÊNCIA
ALTER TABLE pets ADD COLUMN IF NOT EXISTS emergency_vet_name VARCHAR(200);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS emergency_vet_phone VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS emergency_vet_address TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS severe_allergies TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS medical_conditions TEXT;

-- ÍNDICES IMPORTANTES
CREATE INDEX IF NOT EXISTS idx_pets_energy_level ON pets(energy_level);
CREATE INDEX IF NOT EXISTS idx_pets_room_preference ON pets(room_preference);
CREATE INDEX IF NOT EXISTS idx_pets_dog_sociability ON pets(dog_sociability);

-- ATUALIZAR ESTATÍSTICAS
ANALYZE pets;
